"""Pydantic schemas: enums, sub-task response models, final annotation."""

from __future__ import annotations

from .annotation import (
    Environment,
    FinalAnnotation,
    KeyElement,
    Privacy,
    QAPair,
    RiskLabel,
    TimeSpan,
)
from .enums import (
    CORE_TASKS,
    Action,
    AnswerType,
    CameraMotion,
    Category,
    CrowdLevel,
    Distance,
    Importance,
    Lighting,
    LocationType,
    Motion,
    Position,
    QAType,
    RiskType,
    Severity,
    SourceDataset,
    Split,
    TaskName,
    VideoStatus,
    Walkability,
    Weather,
)
from .subtasks import (
    SUBTASK_MODELS,
    CaptionResponse,
    CurateClassification,
    EntitiesResponse,
    EntityItem,
    EventItem,
    EventsResponse,
    JudgmentResponse,
    QAItem,
    QAResponse,
    RiskItem,
    SceneResponse,
    get_subtask_model,
)

__all__ = [
    "CORE_TASKS",
    "SUBTASK_MODELS",
    "Action",
    "AnswerType",
    "CameraMotion",
    "CaptionResponse",
    "Category",
    "CrowdLevel",
    "CurateClassification",
    "Distance",
    "EntitiesResponse",
    "EntityItem",
    "Environment",
    "EventItem",
    "EventsResponse",
    "FinalAnnotation",
    "Importance",
    "JudgmentResponse",
    "KeyElement",
    "Lighting",
    "LocationType",
    "Motion",
    "Position",
    "Privacy",
    "QAItem",
    "QAPair",
    "QAResponse",
    "QAType",
    "RiskItem",
    "RiskLabel",
    "RiskType",
    "SceneResponse",
    "Severity",
    "SourceDataset",
    "Split",
    "TaskName",
    "TimeSpan",
    "VideoStatus",
    "Walkability",
    "Weather",
    "get_subtask_model",
]
